### PR TITLE
I hate merge errors 2 :disappointed: 

### PR DESCRIPTION
**Pull request by CodeTorso**

### CODE REVIEW

**Comment by Dhravya** [comment]
```
11:55:03.510	error @typescript-eslint/eslint-plugin@7.14.1: The engine "node" is incompatible with this module. Expected version "^18.18.0 || >=20.0.0". Got "18.17.1"
11:55:03.521	error Found incompatible module.
11:55:03.521	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
11:55:03.589	Error: Exit with error code: 1
11:55:03.590	    at ChildProcess.<anonymous> (/snapshot/dist/run-build.js)
11:55:03.590	    at Object.onceWrapper (node:events:652:26)
11:55:03.590	    at ChildProcess.emit (node:events:537:28)
11:55:03.590	    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by Dhravya** [comment]
ok, this won't happen now

**Comment by CodeTorso** [comment]
is there anyway I can see the build errors ?

I will still try to fix it by looking to build it locally, i would have been easy with logs

**Comment by Dhravya** [comment]
This is the reason it happens - I had to bump down the version of eslint-plugin
```
https://github.com/Dhravya/supermemory/blob/619614a9160895a58acc35039a677f0cf2a266c1/packages/eslint-config/package.json#L16-L17
```

**Pull request closed without merging**
